
# This file defines how your Supabase project should be configured
# Bug: https://github.com/orgs/supabase/discussions/11915

project_id = "vmyzceyvkkcgdbgmbbqf"

[api]
enabled = true
port = 54321

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true

[analytics]
enabled = false
port = 54327

[experimental]
enable_realtime = false

[functions]
analyze-business = {}
compliance-buddy-chat = {}
fetch-eurlex-rss = {}
generate-documentation = {}
analyze-regulation-impact = {}
