
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

const SUPABASE_URL = "https://vmyzceyvkkcgdbgmbbqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZteXpjZXl2a2tjZ2RiZ21iYnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMTYwMzQsImV4cCI6MjA1NDU5MjAzNH0.h804WotC8aLH-3EPBRcE3kWPpwkvfZRkI9o2oQdzkBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
